pipeline {
    agent any

    stages {
        stage('Starting') {
            steps {
                echo 'Code starting step..'
            }
        }
        stage('Docker image') {
            steps {
                echo 'Creating docker image'
				script{
					sh 'docker build -t jay96docker/testrepo .'
				}
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
